language: python
python:
  # - "2.7"
  - "3.3"
  - "3.4"
# command to install dependencies
install: 
    - pip install coveralls
    # - pip install -r requirements.txt
    - python setup.py install
# command to run tests
script: 
    coverage run --source=vigilance setup.py test 

after_success:
    coveralls